### ISSUE TITLE
`put_time` not part of `std` in g++4.8

### ISSUE THREAD

**Issue by The-EDev** [CrowCpp/Crow#463]
```
$ g++-4.8 example_with_all.cpp -std=c++11 -lpthread -o examp
In file included from example_with_all.cpp:1:0:
crow_all.h: In member function ‘std::string crow::CookieParser::Cookie::dump() const’:
crow_all.h:5537:27: error: ‘put_time’ is not a member of ‘std’
                        << std::put_time(expires_at_.get(), HTTP_DATE_FORMAT);
                           ^
```
it looks like the code doesn't compile with GCC4.8's c++11, which is either a bug in GCC or a missing feature from c++11

**Comment by The-EDev** [comment]
Crow v1.1 will not officially support GCC < 5. A the moment only the cookie parser middleware doesn't work with GCC 4.8. Closing this issue unless full GCC 4.8 support is determined to be absolutely necessary.
