### ISSUE TITLE
Can' t not build in link parse cause multiple definition.

### ISSUE THREAD

**Issue by cdwdong** [CrowCpp/Crow#390]
Can' t not build in link parse cause multiple definition.

linker log :   
```
1>Linking objects
1>D:\dev\office_work\TestProject_App_Linux\TestProject_Linux\obj\x64\Debug\WebService.o : error : In function `crow::CORSRules::prefix(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
1>D:\dev\office_work\TestProject_App_Linux\TestProject_Linux\crow_all.h(11053): error : multiple definition of `crow::CORSRules::prefix(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
1>D:\dev\office_work\TestProject_App_Linux\TestProject_Linux\obj\x64\Debug\main.o : error : /home/kai/projects/TestProject_App/crow_all.h:11053: first defined here
1>D:\dev\office_work\TestProject_App_Linux\TestProject_Linux\obj\x64\Debug\WebService.o : error : In function `crow::CORSRules::blueprint(crow::Blueprint const&)':
1>D:\dev\office_work\TestProject_App_Linux\TestProject_Linux\crow_all.h(11058): error : multiple definition of `crow::CORSRules::blueprint(crow::Blueprint const&)'
1>D:\dev\office_work\TestProject_App_Linux\TestProject_Linux\obj\x64\Debug\main.o : error : /home/kai/projects/TestProject_App/crow_all.h:11058: first defined here
1>D:\dev\office_work\TestProject_App_Linux\TestProject_Linux\obj\x64\Debug\WebService.o : error : In function `crow::CORSRules::global()':
1>D:\dev\office_work\TestProject_App_Linux\TestProject_Linux\crow_all.h(11063): error : multiple definition of `crow::CORSRules::global()'
1>D:\dev\office_work\TestProject_App_Linux\TestProject_Linux\obj\x64\Debug\main.o : error : /home/kai/projects/TestProject_App/crow_all.h:11063: first defined here
1>collect2 : error : ld returned 1 exit status
1>Done building project "TestProject_Linux.vcxproj" -- FAILED.
```  
It was build in gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0  
i use MSBuild c++ cross platform compile

**Comment by The-EDev** [comment]
@dranikpg It seems the CORS middleware isn't designed to work with multiple source files, I'll try to look into it but I'd be thankful for help.

**Comment by jeanbiber** [comment]
I had yesterday the samme issue. My solution was to write "inline" before the functions-impementations and it worked for me.
cors.h: from line 185

inline CORSRules& CORSRules::prefix(const std::string& prefix)
    {
        return handler_->prefix(prefix);
    }

    inline CORSRules& CORSRules::blueprint(const Blueprint& bp)
    {
        return handler_->blueprint(bp);
    }

    inline CORSRules& CORSRules::global()
    {
        return handler_->global();
    }

**Comment by The-EDev** [comment]
The issue is that the declaration and definitions for `CORSRules` are separate, and so the definitions get repeated when using more than 1 source file.

**Comment by jeanbiber** [comment]
I mean that Inside the class a declaration is considered to be inline by the compiler. If you implement outside of body, but still in header, you have to mark the method as 'inline' explicitly.

struct CORSRules
 {
      /// Handle CORS for specific blueprint
      CORSRules& blueprint(const Blueprint& bp);
}
inline CORSRules& CORSRules::blueprint(const Blueprint& bp)
{
    return handler_->blueprint(bp);
}

**Comment by dranikpg** [comment]
Sorry for the late response. I must have missed this when refactoring them out of the class. 
Thanks for pointing out the fix! 👍🏻
